sudo: required

language: python

services:
  - postgresql
  
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to create database
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres

# command to run tests
script:
  - python manage.py test
