sudo: required

language: python

services:
  - postgresql
  
python:
  - "3.7-dev"  # development branch

# command to install dependencies
install:
  - pip install codecov && pip install -r requirements.txt

# command to create database
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres

# command to run tests
script:
  - coverage run manage.py test

# run coverage
after_success:
  - codecov -t $CODECOV_TOKEN
