version: "3"
services:
  web:
    build: .
    container_name: web
    env_file:
      - .env
    command: ["./wait-for-it.sh", "db", "user", "test", "backandbeyond"]
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres:9.6-alpine
    container_name: db
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=backandbeyond
    ports:
      - "5432:5432"
