# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='text',
            new_name='html_text',
        ),
        migrations.AddField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posts',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 20, 21, 3, 7, 352819, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='markdown_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
