# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20151220_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.IntegerField(choices=[(1, b'Draft'), (2, b'Published'), (3, b'Private'), (4, b'Archived')], default=1),
        ),
    ]
