# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttags',
            options={'verbose_name_plural': 'post tags'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(through='blog.PostTags', to='blog.Tag'),
        ),
    ]
