# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170418_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-date_created', '-last_updated'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='html_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='markdown_text',
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
