# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170702_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='markdown_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='html_content',
        ),
    ]
