# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 21, 19, 44, 498788, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 5, 23, 21, 19, 56, 701461, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
