# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170523_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
