name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: test
          POSTGRES_DB: backandbeyond
        ports:
          - 5432:5432
        options: --health-cmd pg_is_ready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: psycopg2 prerequisites
      run: sudo apt install python-dev libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codecov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run migrations
      run: python manage.py migrate
